# docker-compose.yml

version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: golang
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  go_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    depends_on:
      - db
    ports:
      - "8082:8082"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: 1234
      DB_NAME: golang